
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, } from "next/font/google";

import "./globals.css";
import { Layout } from "../components/Layout";


export const metadata: Metadata = {
  title: "Web Profile",
  description: "Generated by create next app",
};


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});



export default function RootLayout({
    children,
}: Readonly<{ children: ReactNode }>) {


    return (
        <html lang="en" className={`${geistSans.variable} scroll-smooth` }>
            <Layout >
                {children}
            </Layout>
        </html>
    );
}
